name: base
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD-root}
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: spring_rest_api_base
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - base
    volumes:
      - ./data/mysql:/var/lib/mysql
      # - ./shopping.sql:/docker-entrypoint-initdb.d/shopping.sql
networks:
  base: